# Generated by Django 4.2.4 on 2023-09-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image'),
        ('blog', '0006_post_views'),
    ]

    operations = [
    ]
