# Generated by Django 4.2.4 on 2023-09-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_dislikes_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dislikes',
            new_name='comment_dislikes',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='comment_likes',
        ),
    ]
