# Generated by Django 4.2.4 on 2023-10-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_dislikes_comment_comment_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
